// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ_1fOyZAk2oMb91-9V8w_vonLgYxysLY',
    appId: '1:147404841026:web:5ac0965c759c37b6818ddb',
    messagingSenderId: '147404841026',
    projectId: 'time-care-642b1',
    authDomain: 'time-care-642b1.firebaseapp.com',
    databaseURL: 'https://time-care-642b1-default-rtdb.firebaseio.com',
    storageBucket: 'time-care-642b1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy4FRG12XFK5ggNbZvTFyUKXTtAemLTvY',
    appId: '1:147404841026:android:043c48e1a47febf0818ddb',
    messagingSenderId: '147404841026',
    projectId: 'time-care-642b1',
    databaseURL: 'https://time-care-642b1-default-rtdb.firebaseio.com',
    storageBucket: 'time-care-642b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6ytva6ojUiIwJ6Lt4g-_I_Z3CvPc2Vmw',
    appId: '1:147404841026:ios:0861d2df6e8af732818ddb',
    messagingSenderId: '147404841026',
    projectId: 'time-care-642b1',
    databaseURL: 'https://time-care-642b1-default-rtdb.firebaseio.com',
    storageBucket: 'time-care-642b1.firebasestorage.app',
    iosBundleId: 'com.example.timecare',
  );
}
